### PR TITLE
Include some of my commits maybe?

### PR DESCRIPTION
**Pull request by Furrydaus**
I think its time we all collaborated lmao.
Some commits here should be included in the Official CM Source Code especially the Screen Brightness. Its been an annoyance to be looking at the phone screen with that 'lowest' brightness setting. Other than that, the other commits can be applied. Up to you. Those under /custom are custom patches from XDA. Feel free to reverse engineer and include em in the code.

Regards,
Furrydaus

### CODE REVIEW

**Comment by brinlyau** [comment]
Can you please submit any of these upstream to CM gerrit??

Squash and submit to Gerrit then i'm happy to review for you (make sure you add me as a reviewer or I won't get notified).

**Comment by Furrydaus** [comment]
I need a crash course for CM Gerrit hahaha. Haven't used it in like ages.
Maybe another time if it has to go through the CM Gerrit. Lemme finish finalizing the LBL Sources first bahaha

**Comment by nosedive** [comment]
hello @Furrydaus,
you have lots of nice commits here. i would love to see some of the in my repo. sure i'm going to give proper credit.. but some more collaboration will be very helpful for all of us ;-)
maybe you find some of mine useful too? 
cheers

**Comment by brinlyau** [comment]
Abandon this.

**Pull request closed without merging**
